// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SD_340_W22SD_Lab_3.Data;

#nullable disable

namespace SD_340_W22SD_Lab_3.Migrations
{
    [DbContext(typeof(SD_340_W22SD_Lab_3Context))]
    [Migration("20220913005044_InitialCreateModels")]
    partial class InitialCreateModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SD_340_W22SD_Lab_3.Models.Direction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("Direction");
                });

            modelBuilder.Entity("SD_340_W22SD_Lab_3.Models.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("BicycleAccessible")
                        .HasColumnType("bit");

                    b.Property<int>("DirectionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<bool>("RampAccessible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DirectionId");

                    b.ToTable("Route");
                });

            modelBuilder.Entity("SD_340_W22SD_Lab_3.Models.ScheduledStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("RouteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScheduledArrival")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.HasIndex("StopId");

                    b.ToTable("ScheduledStop");
                });

            modelBuilder.Entity("SD_340_W22SD_Lab_3.Models.Stop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DirectionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DirectionId");

                    b.ToTable("Stop");
                });

            modelBuilder.Entity("SD_340_W22SD_Lab_3.Models.Route", b =>
                {
                    b.HasOne("SD_340_W22SD_Lab_3.Models.Direction", "Direction")
                        .WithMany()
                        .HasForeignKey("DirectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Direction");
                });

            modelBuilder.Entity("SD_340_W22SD_Lab_3.Models.ScheduledStop", b =>
                {
                    b.HasOne("SD_340_W22SD_Lab_3.Models.Route", "Route")
                        .WithMany("ScheduledStops")
                        .HasForeignKey("RouteId");

                    b.HasOne("SD_340_W22SD_Lab_3.Models.Stop", "Stop")
                        .WithMany("StopSchedules")
                        .HasForeignKey("StopId");

                    b.Navigation("Route");

                    b.Navigation("Stop");
                });

            modelBuilder.Entity("SD_340_W22SD_Lab_3.Models.Stop", b =>
                {
                    b.HasOne("SD_340_W22SD_Lab_3.Models.Direction", "Direction")
                        .WithMany()
                        .HasForeignKey("DirectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Direction");
                });

            modelBuilder.Entity("SD_340_W22SD_Lab_3.Models.Route", b =>
                {
                    b.Navigation("ScheduledStops");
                });

            modelBuilder.Entity("SD_340_W22SD_Lab_3.Models.Stop", b =>
                {
                    b.Navigation("StopSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
