// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SD_340_W22SD_Lab_3.Data;

#nullable disable

namespace SD_340_W22SD_Lab_3.Migrations
{
    [DbContext(typeof(SD_340_W22SD_Lab_3Context))]
    partial class SD_340_W22SD_Lab_3ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SD_340_W22SD_Lab_3.Models.Direction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("Directions");
                });

            modelBuilder.Entity("SD_340_W22SD_Lab_3.Models.Route", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Number"), 1L, 1);

                    b.Property<bool?>("BicycleAccessible")
                        .HasColumnType("bit");

                    b.Property<int?>("DirectionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("RampAccessible")
                        .HasColumnType("bit");

                    b.HasKey("Number");

                    b.HasIndex("DirectionId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("SD_340_W22SD_Lab_3.Models.ScheduledStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("RouteNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScheduledArrival")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StopNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RouteNumber");

                    b.HasIndex("StopNumber");

                    b.ToTable("ScheduledStops");
                });

            modelBuilder.Entity("SD_340_W22SD_Lab_3.Models.Stop", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Number"), 1L, 1);

                    b.Property<int?>("DirectionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Number");

                    b.HasIndex("DirectionId");

                    b.ToTable("Stop");
                });

            modelBuilder.Entity("SD_340_W22SD_Lab_3.Models.Route", b =>
                {
                    b.HasOne("SD_340_W22SD_Lab_3.Models.Direction", "Direction")
                        .WithMany()
                        .HasForeignKey("DirectionId");

                    b.Navigation("Direction");
                });

            modelBuilder.Entity("SD_340_W22SD_Lab_3.Models.ScheduledStop", b =>
                {
                    b.HasOne("SD_340_W22SD_Lab_3.Models.Route", "Route")
                        .WithMany("StopSchedules")
                        .HasForeignKey("RouteNumber");

                    b.HasOne("SD_340_W22SD_Lab_3.Models.Stop", "Stop")
                        .WithMany("StopSchedules")
                        .HasForeignKey("StopNumber");

                    b.Navigation("Route");

                    b.Navigation("Stop");
                });

            modelBuilder.Entity("SD_340_W22SD_Lab_3.Models.Stop", b =>
                {
                    b.HasOne("SD_340_W22SD_Lab_3.Models.Direction", "Direction")
                        .WithMany()
                        .HasForeignKey("DirectionId");

                    b.Navigation("Direction");
                });

            modelBuilder.Entity("SD_340_W22SD_Lab_3.Models.Route", b =>
                {
                    b.Navigation("StopSchedules");
                });

            modelBuilder.Entity("SD_340_W22SD_Lab_3.Models.Stop", b =>
                {
                    b.Navigation("StopSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
